# Generated by Django 4.2.16 on 2024-09-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_alter_assessment_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="question",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
