# Generated by Django 4.2.16 on 2024-11-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_alter_assessment_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="correct_answer",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=3
            ),
        ),
    ]
