# Generated by Django 4.2.16 on 2024-10-29 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milestones", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="milestone",
            name="category",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="child_id",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="is_current",
        ),
        migrations.AddField(
            model_name="milestone",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="milestone",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="milestones/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="summary",
            field=models.JSONField(default=""),
        ),
    ]
