# Generated by Django 4.2.16 on 2024-10-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "milestones",
            "0002_remove_milestone_category_remove_milestone_child_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="summary",
            field=models.JSONField(default=dict),
        ),
    ]
