# Generated by Django 4.2.16 on 2024-10-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milestones", "0003_alter_milestone_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="summary",
            field=models.JSONField(),
        ),
    ]
