# Generated by Django 5.1.1 on 2024-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autism_Image',
            fields=[
                ('image_id', models.PositiveSmallIntegerField(primary_key=1, serialize=False)),
                ('child_id', models.IntegerField()),
                ('image_upload', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
