# Generated by Django 4.2.16 on 2024-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autism_Image',
            fields=[
                ('image_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('child_id', models.IntegerField()),
                ('image_upload', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
