# Generated by Django 5.1.1 on 2024-09-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autism_image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='autism_image',
            name='image_upload',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='autism_image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
