# Generated by Django 4.2.16 on 2024-09-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0004_alter_child_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="parent",
        ),
    ]
