# Generated by Django 5.1.1 on 2024-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='avatar_picture',
        ),
        migrations.RemoveField(
            model_name='child',
            name='is_active',
        ),
        migrations.AddField(
            model_name='child',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='child_profiles/'),
        ),
        migrations.AlterField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
