# Generated by Django 5.1.1 on 2024-09-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_remove_child_avatar_picture_remove_child_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
