# Generated by Django 5.1.1 on 2024-09-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_alter_child_created_at_alter_child_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
