# Generated by Django 4.2.16 on 2024-09-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_alter_child_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
