# Generated by Django 4.2.16 on 2024-09-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
        ('autism_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autism_image',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='child.child'),
        ),
    ]
