# Generated by Django 4.2.16 on 2024-09-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_initial'),
        ('autism_image', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autism_image',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.child'),
        ),
        migrations.AlterField(
            model_name='autism_image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='autism_image',
            name='image_upload',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='autism_image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
