# Generated by Django 4.2.16 on 2024-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_image', '0003_alter_autism_image_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autism_image',
            name='image_upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
