# Generated by Django 4.2.16 on 2024-09-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autism_image", "0004_alter_autism_image_image_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autism_image",
            name="image_upload",
            field=models.ImageField(upload_to="autism_detector/"),
        ),
    ]
