# Generated by Django 4.2.16 on 2024-09-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("child", "0004_alter_child_date_of_birth"),
        ("autism_image", "0006_alter_autism_image_child"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autism_image",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="child.child"
            ),
        ),
    ]
