# Generated by Django 4.2.16 on 2024-10-29 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="milestone",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="type",
        ),
        migrations.AddField(
            model_name="resource",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="resources/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="activities",
            field=models.JSONField(default=""),
        ),
        migrations.AlterField(
            model_name="resource",
            name="tips",
            field=models.JSONField(default=""),
        ),
    ]
