# Generated by Django 4.2.16 on 2024-10-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_remove_resource_milestone_remove_resource_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="activities",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="resource",
            name="tips",
            field=models.JSONField(default=dict),
        ),
    ]
